### ISSUE TITLE
Unable to login to the google drive 

### ISSUE THREAD

**Issue by Praveer1981** [alexkim205/Google-Drive-Electron#13]
I downloaded `Google.Drive.Electron-win32-ia32.zip ` package and ran in windows 10 machine .

I get below error when I try to login to the google drive

`This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.`

**Comment by alexkim205** [comment]
Thanks for the comment, I'll take a look into it

**Comment by vojtamolda** [comment]
Hello everyone,

I've got the same issue on macOS. This is the screen right after typing my Google account email. I tried to figure out a way around it but no luck so far (i.e. ⌘-R keyboard shortcut to reload the page).

Thanks, @alexkim205, for looking into it and let me know if you need me to run some more tests.

<img width="1084" alt="Login Failure" src="https://user-images.githubusercontent.com/8467740/79032002-9f70b380-7b68-11ea-8e65-b186de995ef6.png">

This is the version (latest) I'm using:
<img width="350" alt="About" src="https://user-images.githubusercontent.com/8467740/79032053-055d3b00-7b69-11ea-9941-aca765a49da9.png">

**Comment by Praveer1981** [comment]
I could resolve this issue by just overwriting the user-agent.

https://github.com/electron/electron/issues/22857
This is how I resolved the issue

Some reference:

https://support.google.com/accounts/thread/22873505?hl=en

**Comment by Praveer1981** [comment]
Hi Alex,
My temp fix will work until google release chrome 81. I heard that user-agent will be taken out in chrome 81.
What would be the another proper solution?
Kind regards 
Praveer.

**Comment by averdet** [comment]
Hello everyone, 
Would it be possible to describe a bit more how to apply this fix ?
I really enjoyed using this Electron wrapper but I can't login anymore.
I don't have much knowledge on Electron but I should be able to follow instructions.
I think this could help others too.

Thank you, take care

**Comment by alexkim205** [comment]
I think the issue is that newer versions of Chrome made OAuth a lot stricter, and phased out any type of authentication done on unsupported browsers including Electron. However there's a couple of workarounds below that involves modifying the request from Electron to fool Google's OAuth servers into thinking its coming from a Chrome browser.

https://pragli.com/blog/how-to-authenticate-with-google-in-electron/
and
https://stackoverflow.com/questions/35672602/how-to-set-electron-useragent

I'll keep you all posted on my progress in this thread, and I appreciate everyone's patience.
