### ISSUE TITLE
No media shown after login

### ISSUE THREAD

**Issue by MiMoHo** [alexkim205/Google-Drive-Electron#9]
Installation and login worked fine. However, I'm unable to see my files stored on Google Drive, though I can browse the folder structure in the left panel.
System: Mac OS X 10.14.3

**Comment by jeremynevans** [comment]
This occurs for me too, and seems to be a recent issue - I'm guessing Google Drive has changed something in the last few weeks.
System: Mac OS X 10.13.6

**Comment by jeremynevans** [comment]
Update: I've fixed this within my own app, and would guess that it'll work here too @alexkim205 @MiMoHo . To solve it, create a `preload.js` script file containing the following:

```
if (!window.chrome) {
  window.chrome = {}
}
```

Then add the following option wherever the BrowserWindow or BrowserView is created, to run the preload script before the page loads:
```
webPreferences: {
  preload: path.join(__dirname, '/preload.js'),
}
```

The issue was that drive.google.com was referencing window.chrome, which didn't exist. (There wasn't a console error though, so I diagnosed it by spotting a Network request to `https://drive.google.com/drive/jserror?script=https%3A%2F%2Fdrive.google.com%2Fdrive%2Fmy-drive&error=chrome%20is%20not%20defined&line=Not%20available`.)

**Comment by alexkim205** [comment]
Thank you for the update. I think this would help a lot of people having the same issue. Would you mind making a pull request?
